language: php

env:
  global:
    - TYPO3_EXTENSION_KEY=html5mediakit

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

stages:
  - test
  - name: deploy
    if: tag

before_script:
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install

jobs:
  include:
    - stage: test
      name: "Composer validate"
      php: "7.3"
      script: bash .Build/bin/t3_run_tests.sh -s composerValidate -p $TRAVIS_PHP_VERSION
    - name: "PHP code sniffer"
      php: "7.3"
      script: bash .Build/bin/t3_check_codestyle.sh PSRHtml5mediakit

    - name: "Unit tests PHP 7.2"
      php: "7.2"
      script: bash .Build/bin/t3_run_tests.sh -s unit -p $TRAVIS_PHP_VERSION
    - name: "Unit tests PHP 7.3"
      php: "7.3"
      script: bash .Build/bin/t3_run_tests.sh -s unit -p $TRAVIS_PHP_VERSION

    - name: "Functional tests on MySQL PHP 7.2"
      php: "7.2"
      script: bash .Build/bin/t3_run_tests.sh -s functional -p $TRAVIS_PHP_VERSION
    - name: "Functional tests on MySQL PHP 7.3"
      php: "7.3"
      script: bash .Build/bin/t3_run_tests.sh -s functional -p $TRAVIS_PHP_VERSION

    - name: "PHP linting PHP 7.2"
      php: "7.2"
      script: bash .Build/bin/t3_run_tests.sh -s lint -p $TRAVIS_PHP_VERSION
    - name: "PHP linting PHP 7.3"
      php: "7.3"
      script: bash .Build/bin/t3_run_tests.sh -s lint -p $TRAVIS_PHP_VERSION

    - name: "Acceptance tests PHP 7.2"
      php: "7.2"
      script: bash .Build/bin/t3_run_tests.sh -s acceptance -p $TRAVIS_PHP_VERSION
    - name: "Acceptance tests PHP 7.3"
      php: "7.3"
      script: bash .Build/bin/t3_run_tests.sh -s acceptance -p $TRAVIS_PHP_VERSION

    - stage: deploy
      name: "Deploy to TER"
      php: "7.3"
      script: bash .Build/bin/t3_deploy_to_ter.sh
