language: php

php:
  - 7.2
  - 7.3

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - Build/Scripts/runTests.sh -s composerInstall -p $TRAVIS_PHP_VERSION

stages:
  - test
  - name: deploy
    if: tag

jobs:
  include:
  - stage: "test"
    name: "Composer validate"
    script: Build/Scripts/runTests.sh -s composerValidate -p $TRAVIS_PHP_VERSION
  - name: "Unit Tests"
    script: Build/Scripts/runTests.sh -s unit -p $TRAVIS_PHP_VERSION
  - name: "Functional test on MySQL"
    script: Build/Scripts/runTests.sh -s functional -p $TRAVIS_PHP_VERSION
  - name: "PHP linting"
    script: Build/Scripts/runTests.sh -s lint -p $TRAVIS_PHP_VERSION
  - name: "PHP code sniffer"
    php: 7.3
    script: Build/Scripts/runCodeStyleChecks.sh

  - stage: "deploy"
    name: "Deploy to TER"
    script: Build/Scripts/deployToTer.sh
