name: Fetch composer dependencies

description: "Fetch composer dependencies from artifact and extract"

inputs:
  php_version:
    required: true
    description: "The PHP version that should be used"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@master
      with:
        name: composer-dependencies-${{ inputs.php_version }}
        path: ./

    - name: Extract Build.tar.gz
      run: tar -xzf Build.tar.gz
      shell: bash

    - name: Remove Build.tar.gz
      run: rm Build.tar.gz
      shell: bash
