name: CI

on:
  push:
  pull_request:

env:
  TYPO3_EXTENSION_KEY: html5mediakit

jobs:
  composer-install:
    runs-on: ubuntu-latest
    container:
      image: typo3gmbh/php${{ matrix.container-version }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    strategy:
      matrix:
        include:
          - container-version: 72
            php-version: 7.2
          - container-version: 73
            php-version: 7.3
          - container-version: 74
            php-version: 7.4
    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        run: composer install

      - name: Create Build.tar
        run: tar -czf Build.tar.gz .Build

      - name: Save dependencies in artifacts
        uses: actions/upload-artifact@master
        with:
          name: composer-dependencies-${{ matrix.php-version }}
          path: Build.tar.gz

  composer-validate:
    needs: composer-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/fetch-composer-dependencies
        with:
          php_version: 7.4

      - name: Validate composer.json
        run: bash .Build/bin/t3_run_tests.sh -s composerValidate -p 7.4

  check-codestyle:
    needs: composer-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/fetch-composer-dependencies
        with:
          php_version: 7.4

      - name: Run codestyle checks
        run: bash .Build/bin/t3_check_codestyle.sh PSRHtml5mediakit

  php-unit:
    needs: composer-install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/fetch-composer-dependencies
        with:
          php_version: ${{ matrix.php-versions }}

      - name: Run codestyle checks
        run: bash .Build/bin/t3_run_tests.sh -s unit -p ${{ matrix.php-versions }}

  php-feature-sqlite:
    needs: composer-install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/fetch-composer-dependencies
        with:
          php_version: ${{ matrix.php-versions }}

      - name: Run codestyle checks
        run: bash .Build/bin/t3_run_tests.sh -s functional -d sqlite -p ${{ matrix.php-versions }}

  php-feature-mysql:
    needs: composer-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/fetch-composer-dependencies
        with:
          php_version: 7.4

      - name: Run codestyle checks
        run: bash .Build/bin/t3_run_tests.sh -s functional -p 7.4

  php-acceptance:
    needs: composer-install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/fetch-composer-dependencies
        with:
          php_version: ${{ matrix.php-versions }}

      - name: Run acceptance tests
        run: bash .Build/bin/t3_run_tests.sh -s acceptance -p ${{ matrix.php-versions }}

  php-lint:
    needs: composer-install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/fetch-composer-dependencies
        with:
          php_version: ${{ matrix.php-versions }}

      - name: Run PHP linting
        run: bash .Build/bin/t3_run_tests.sh -s lint -p ${{ matrix.php-versions }}
