---
name: Testing and linting

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '45 8 * * 6'

env:
  TYPO3_EXTENSION_KEY: html5mediakit
  MAIN_PHP_VERSION: 8.3
  CI: true

jobs:
  extension-test:
    name: 'Testing and linting'
    uses: astehlik/typo3-extension-buildtools/.github/workflows/extension-test.yml@TYPO3_13

  extension-cc-coverage:
    name: 'Code Climate coverage'
    uses: astehlik/typo3-extension-buildtools/.github/workflows/extension-cc-coverage.yml@TYPO3_13
    if: github.ref == 'refs/heads/develop'
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
